name: GitOps Promote

on:
  workflow_call:
    inputs:
      tag:
        description: "Set Docker Image Tag"
        required: true  
        type: string
      repository:
        description: "Set Repository Name"
        required: true  
        type: string
      url:
        description: "Set Project URL"
        required: true  
        type: string
      environment:
        description: "Set Project Environment"
        required: true  
        type: string        

jobs:
  deploy:
    name: GitOps Deploy
    runs-on: ubuntu-latest
    environment: 
      name: '${{ inputs.environment }}'
      url: '${{ inputs.url }}'

    steps:
    - name: Set Kustomize
      uses: imranismail/setup-kustomize@v2
      with:
        kustomize-version: "3.9.4"

    - name: GitOps Checkout
      run: git clone https://github.com/paulofponciano/EKS-Crossplane-ArgoCD.git .

    - name: Update Docker Image Tag
      run: |
        NEW_TAG=$(cat deployed_apps/${{ inputs.repository }}/overlays/kustomization.yaml | grep 'tag:' |  awk '{print $2}')
        OLD_TAG=$(cat deployed_apps/${{ inputs.repository }}/overlays/kustomization.yaml | grep 'tag:' |  awk '{print $2}')
        sed -i "s|$OLD_TAG|$NEW_TAG|g" deployed_apps/${{ inputs.repository }}/overlays/kustomization.yaml

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "[ci skip] :robot: Set New Image Tag to https://github.com/${{ github.repository }}/commit/${{ inputs.tag }}"
        git push